In [5]:
A = 12
B= 11
("banu earns {} and srinu earns {}".format(A, B))


'banu earns 12 and srinu earns 11'

In [6]:
print ("banu earns {US} and srinu earns {RS}".format(US=A, RS=B))

banu earns 12 and srinu earns 11


In [7]:
A= 'asdefrdsdff76548'
print (A[0:8])

asdefrds


In [8]:
def countdog(str):
    count = 0
    for word in str.split():
        if word == 'dog':
            count +=1
    return count
countdog("Hey dog this is dog i am a dog")

3

In [9]:
A= str(input("characters:"))
def wordcount (A):
    count = 0
    words = A.split()
    for word in words:
        if word == 'DOG':
           count+=1
    return count
print(wordcount(A))

characters: asd


0


In [10]:
### NUMPY ARRAY'S METHODS ###

In [11]:
import numpy as np
my_list = [1,1,2,3,4,5]
arr = np.array(my_list)
arr

array([1, 1, 2, 3, 4, 5])

In [12]:
np.arange(3,50,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49])

In [13]:
# to get a numbers in a range between 0 to 10 using np -- arange()

np.arange(0,10)

# step in range between numbers here 3 isthe step size
np.arange(2,18,3)

array([ 2,  5,  8, 11, 14, 17])

In [14]:
# creating 2d matrix in np with passing tupple()
np.ones((4,4))
np.zeros((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# numpy has inbult linspace -- the count start increse by .number wise in a single matrix
np.linspace(2,5,6)

array([2. , 2.6, 3.2, 3.8, 4.4, 5. ])

In [16]:
np.eye(6,6,k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.eye(6,8,k=-2)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

In [18]:
## 2D array using random.rand method
np.random.rand(2,5,4)

array([[[0.89507037, 0.76937681, 0.36622952, 0.19962417],
        [0.0633226 , 0.27073841, 0.3095255 , 0.12654877],
        [0.07603499, 0.66049966, 0.61288703, 0.59474774],
        [0.88570882, 0.36482039, 0.6162152 , 0.28119679],
        [0.10394565, 0.97852249, 0.31926848, 0.04025975]],

       [[0.74956882, 0.1520402 , 0.62487169, 0.15967648],
        [0.6156292 , 0.73197995, 0.03778293, 0.57160071],
        [0.75917466, 0.58060432, 0.23213725, 0.08574009],
        [0.03201491, 0.0344134 , 0.54911129, 0.89683915],
        [0.91057098, 0.19095792, 0.7264794 , 0.79202445]]])

In [19]:
#2D array using random.randn methos
np.random.randn(2,3,4)

array([[[ 2.1589384 ,  0.62249492,  0.6885903 , -1.79560452],
        [ 1.02708374, -1.69567744,  0.22015902,  1.79051974],
        [ 0.3876696 , -0.42909815,  0.37966606, -0.69606308]],

       [[ 0.48181456, -0.70599453, -0.7867799 , -0.22844007],
        [-1.41959045,  0.38612497, -0.58407993,  2.07654403],
        [-1.10676213,  1.37922203,  0.70097137,  1.44829008]]])

In [20]:
#3d array using standard normal distribution --- random.randn methos
np.random.randn(2,2,2,3,4)

array([[[[[-0.32738756, -0.11715806,  0.9345779 ,  0.22487866],
          [ 0.7378447 , -0.25409049, -0.26963899,  1.03824789],
          [ 0.23094352, -1.41834199, -0.43039149,  1.13191987]],

         [[-0.47340208, -0.07049276, -1.22976286,  1.04310754],
          [-0.10800717, -0.5796726 ,  1.84662626,  2.70099789],
          [ 0.63112615, -1.93126527,  0.06698098,  0.58867508]]],


        [[[-0.27679498,  0.7443806 ,  0.8809118 ,  0.45585802],
          [-1.48286537,  0.08693625,  0.03986781,  2.505927  ],
          [-1.76932552,  0.10938714, -1.04602998, -0.28700525]],

         [[-0.59018751,  1.30663406, -0.85887655,  1.2162559 ],
          [ 0.64155835,  0.53811262, -1.4033477 , -0.71590942],
          [-0.00272552, -0.93890922,  0.09631125, -1.25107097]]]],



       [[[[ 0.60547925, -0.18637824,  1.05756499, -0.0502893 ],
          [-0.73144773, -0.32610389,  0.53178031, -0.13813004],
          [ 0.7189666 , -0.4670663 ,  0.24091111, -0.25723776]],

         [[ 0.84882884, 

In [21]:
# random intigers 
np.random.randint(20,30,8)

array([24, 29, 21, 28, 22, 26, 28, 26])

In [22]:
# reshape method

A = np.arange(36)
A.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [23]:
rand= np.random.rand(2,20,5)
rand

array([[[0.91143478, 0.22341714, 0.48345853, 0.99929857, 0.6066847 ],
        [0.26872773, 0.1180795 , 0.22262809, 0.84832855, 0.70528011],
        [0.78611755, 0.19114181, 0.18285299, 0.24931129, 0.84820665],
        [0.76909997, 0.85363744, 0.69881037, 0.24472154, 0.05802468],
        [0.58249318, 0.54872554, 0.18756958, 0.05580293, 0.85457561],
        [0.76995496, 0.67147186, 0.87527574, 0.91761765, 0.14868872],
        [0.48492299, 0.6993419 , 0.05925307, 0.33614836, 0.53363637],
        [0.6343084 , 0.04962725, 0.12169591, 0.87345596, 0.79435952],
        [0.60903319, 0.78070067, 0.6654216 , 0.56398912, 0.03857161],
        [0.25460348, 0.80622041, 0.16881661, 0.97669974, 0.1692764 ],
        [0.83254275, 0.07663009, 0.56394549, 0.66275843, 0.76309445],
        [0.21436094, 0.37005887, 0.26017217, 0.05767939, 0.54469285],
        [0.95386971, 0.52699897, 0.86681704, 0.53970498, 0.26571885],
        [0.99230713, 0.41640103, 0.08766439, 0.21196544, 0.04863038],
        [0.43370421,

In [24]:
## findina minimum and maximum values in a matrix or array
rand.min()
rand.max()

0.9992985658452599

In [25]:
# index of an highest value and minimul value
rand.argmax()
rand.argmin()

114

In [26]:
#to find shape of an array or matrix

rand.shape

# to find the datatype

rand.dtype

dtype('float64')

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
################## NUMPY INDEXING AND SELECTION ######################

In [29]:
import numpy as np

In [30]:
B=np.arange(1,30)
B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
B[:15]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
Arr = [-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
A = np.array(Arr)
A

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17])

In [33]:
## passing the value in between the range operator 
A[2:7] = 77
A[0:2] = 22
A[-1] = 34

In [34]:
## array saving/copy() of the values in the range
A_copy = A.copy()

A

array([22, 22, 77, 77, 77, 77, 77,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 34])

In [35]:
## 2d array 3-rows and 3-columns in a matrix

arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
## index/position in a matrix
arr_2d[1] ## displays the entair row of an matrix


array([20, 25, 30])

In [37]:
arr_2d[0,1] ## one way to display a value in a array

10

In [38]:
##2nd way to display exact value 25 & 15 in a matric
arr_2d[1][1] # it displays value 25
arr_2d[0][2] # it displays value 15
arr_2d[1:2,1:2]

array([[25]])

In [39]:
## displaying values using slice notation[:] 
arr_2d[1:3,1:3]

array([[25, 30],
       [40, 45]])

In [40]:
## pratice --1 ##
A=np.arange(50)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
# reshaping the 1d array into 5 rows and 10 cloumns
s = A.reshape(5,10)
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
## extracting the certain in between values form 1D array
s[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [43]:
## pratice -- 2
p=np.arange(50,100).reshape(5,10)
p

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [44]:
p[1:4,2:8]

array([[62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77],
       [82, 83, 84, 85, 86, 87]])

In [45]:
########## NUMPY Operations ##########
##### Array with array ######
### Array with Scalars ###
## Universal Array Functions ##

In [46]:
## Arthematic Operations + - * ** / %
A = np.arange(0,50)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [47]:
A * A
A + A
A - A
A/A
A-1
A ** 2
np.sin(A)
A-2

C:\Users\AkhilPokuri\AppData\Local\Temp\ipykernel_20808\1755926585.py:4: RuntimeWarning: invalid value encountered in divide
  A/A


array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [48]:
np.max(A)
np.min(A)
np.argmax(A)
np.argmin(A)

0

In [49]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
mat.sum() ## it results sum of matrix value
mat.sum(axis=0) ## results in a sum of every colum in a row

array([55, 60, 65, 70, 75])

In [51]:


#################### PANDAS ################## 



In [52]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [53]:
import pandas as pd

In [54]:
## data formats
labels = ['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'A':10, 'B': 20, 'C': 30}

In [55]:
## Series works with 1D- array 
pd.Series(data=d,index=d,name= "it's a one d type")

A    10
B    20
C    30
Name: it's a one d type, dtype: int64

In [56]:
pd.Series(d)

A    10
B    20
C    30
dtype: int64

In [57]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int32

In [58]:
ser1=pd.Series([91,21,32,44],["IN","USA","UE","DE",])

In [59]:
ser1

IN     91
USA    21
UE     32
DE     44
dtype: int64

In [60]:
ser2= pd.Series([1,2,3,4],["IN","Rusya","UE","China"])

In [61]:
ser2
ser2['Rusya']

2

In [62]:
ser3=pd.Series(ser2)
ser3

IN       1
Rusya    2
UE       3
China    4
dtype: int64

In [63]:
A=ser1+ser2
A

China     NaN
DE        NaN
IN       92.0
Rusya     NaN
UE       35.0
USA       NaN
dtype: float64

In [64]:
#### DATAFRAMES######
import numpy as np
from numpy.random import randn
np.random.seed(101)

In [65]:
df = pd.DataFrame(randn(5,5),['A','B','C','D','E'],['F','G','H','I','J'])

In [66]:
df

F         G         H         I         J
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [67]:
type(df)

pandas.core.frame.DataFrame

In [68]:
df[["G","J"]]
df['G']

A    0.628133
B   -0.848077
C   -0.589001
D    0.190794
E    1.693723
Name: G, dtype: float64

In [69]:
df['New']=df['G'] + df ['I']
df

F         G         H         I         J       New
A  2.706850  0.628133  0.907969  0.503826  0.651118  1.131958
B -0.319318 -0.848077  0.605965 -2.018168  0.740122 -2.866245
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237 -1.347873
D  0.955057  0.190794  1.978757  2.605967  0.683509  2.796762
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841  0.534604

In [70]:
df.drop('New', axis=1,inplace=True)
df

F         G         H         I         J
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [71]:

#df.drop('A',inplace=True)
## axis=0-- for rows's and axis=1 -- for column's
##inplace= True-- to save the changes and inplace = False -- doesnt save th changes

df.shape

(5, 5)

In [72]:
## grabing a rows using Loc[] or iloc[]
df.loc['C']
df.iloc[0]

F    2.706850
G    0.628133
H    0.907969
I    0.503826
J    0.651118
Name: A, dtype: float64

In [73]:
## grabing values by row and cloumn
df.loc['A','F']

2.706849839399938

In [74]:
## grabing set of rows and columns in between

df.loc[['B','D','C'],['G','H']]

G         H
B -0.848077  0.605965
D  0.190794  1.978757
C -0.589001  0.188695

In [75]:
df

F         G         H         I         J
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [76]:
## Conditional selections in DataFrames

df>0

F      G      H      I      J
A   True   True   True   True   True
B  False  False   True  False   True
C   True  False   True  False  False
D   True   True   True   True   True
E   True   True  False  False  False

In [77]:
CS=df>0
CS
df[CS]

F         G         H         I         J
A  2.706850  0.628133  0.907969  0.503826  0.651118
B       NaN       NaN  0.605965       NaN  0.740122
C  0.528813       NaN  0.188695       NaN       NaN
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723       NaN       NaN       NaN

In [78]:
df[df > 0]


F         G         H         I         J
A  2.706850  0.628133  0.907969  0.503826  0.651118
B       NaN       NaN  0.605965       NaN  0.740122
C  0.528813       NaN  0.188695       NaN       NaN
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723       NaN       NaN       NaN

In [79]:
df[df['F']>0]


F         G         H         I         J
A  2.706850  0.628133  0.907969  0.503826  0.651118
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [80]:
S = df[df['J']<0]
S['J']

C   -0.933237
E   -0.134841
Name: J, dtype: float64

In [81]:
df[df['H']>=0][['H','I']]

H         I
A  0.907969  0.503826
B  0.605965 -2.018168
C  0.188695 -0.758872
D  1.978757  2.605967

In [82]:
#df[(df['H']>0) & df(df['I']>1)]
#df[(df['H']>0) | df(df['I']>1)]

In [83]:
df.reset_index()

index         F         G         H         I         J
0     A  2.706850  0.628133  0.907969  0.503826  0.651118
1     B -0.319318 -0.848077  0.605965 -2.018168  0.740122
2     C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
3     D  0.955057  0.190794  1.978757  2.605967  0.683509
4     E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [84]:
## using split method insted of using list to assign values
A='US UK GB FR IN'.split()
## adding new column as 'COUNTRY'
df['COUNTRY'] = A
df

F         G         H         I         J COUNTRY
A  2.706850  0.628133  0.907969  0.503826  0.651118      US
B -0.319318 -0.848077  0.605965 -2.018168  0.740122      UK
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237      GB
D  0.955057  0.190794  1.978757  2.605967  0.683509      FR
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841      IN

In [85]:
df.set_index('COUNTRY')

##to save the changes intrept=True

#df.set_index('country',inplace=True)

F         G         H         I         J
COUNTRY                                                  
US       2.706850  0.628133  0.907969  0.503826  0.651118
UK      -0.319318 -0.848077  0.605965 -2.018168  0.740122
GB       0.528813 -0.589001  0.188695 -0.758872 -0.933237
FR       0.955057  0.190794  1.978757  2.605967  0.683509
IN       0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [86]:
## to reset back the changes of undex

df.reset_index()

index         F         G         H         I         J COUNTRY
0     A  2.706850  0.628133  0.907969  0.503826  0.651118      US
1     B -0.319318 -0.848077  0.605965 -2.018168  0.740122      UK
2     C  0.528813 -0.589001  0.188695 -0.758872 -0.933237      GB
3     D  0.955057  0.190794  1.978757  2.605967  0.683509      FR
4     E  0.302665  1.693723 -1.706086 -1.159119 -0.134841      IN

In [87]:
df.to_string()

'          F         G         H         I         J COUNTRY\nA  2.706850  0.628133  0.907969  0.503826  0.651118      US\nB -0.319318 -0.848077  0.605965 -2.018168  0.740122      UK\nC  0.528813 -0.589001  0.188695 -0.758872 -0.933237      GB\nD  0.955057  0.190794  1.978757  2.605967  0.683509      FR\nE  0.302665  1.693723 -1.706086 -1.159119 -0.134841      IN'

In [88]:
################################## DATAFRAMING -- MULTYINDEXING AND INDEX HIGHERKEY #######################################################

In [89]:
outside = ['G1','G1','G1','G2','G2','G2',]
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [90]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df

A         B
G1 1  0.390528  0.166905
   2  0.184502  0.807706
   3  0.072960  0.638787
G2 1  0.329646 -0.497104
   2 -0.754070 -0.943406
   3  0.484752 -0.116773

In [91]:
df.loc['G1'].loc[2]

A    0.184502
B    0.807706
Name: 2, dtype: float64

In [92]:
df.index.names  = ['Groups','Values']

In [93]:
df.index.names

FrozenList(['Groups', 'Values'])

In [94]:
df

A         B
Groups Values                    
G1     1       0.390528  0.166905
       2       0.184502  0.807706
       3       0.072960  0.638787
G2     1       0.329646 -0.497104
       2      -0.754070 -0.943406
       3       0.484752 -0.116773

In [95]:
# Displaying the pirtuclar value
df.loc['G2'].loc[[2],['B']]
df.loc['G2'].loc[2]['B']

-0.9434064032519315

In [96]:
df

A         B
Groups Values                    
G1     1       0.390528  0.166905
       2       0.184502  0.807706
       3       0.072960  0.638787
G2     1       0.329646 -0.497104
       2      -0.754070 -0.943406
       3       0.484752 -0.116773

In [97]:
## .xs work like loc but .xs perform much more better for complex on multiIndexing
df.xs

<bound method NDFrame.xs of                       A         B
Groups Values                    
G1     1       0.390528  0.166905
       2       0.184502  0.807706
       3       0.072960  0.638787
G2     1       0.329646 -0.497104
       2      -0.754070 -0.943406
       3       0.484752 -0.116773>

In [98]:
df.xs(2,level='Values')

A         B
Groups                    
G1      0.184502  0.807706
G2     -0.754070 -0.943406

In [99]:
df.xs(3,level='Values')

A         B
Groups                    
G1      0.072960  0.638787
G2      0.484752 -0.116773

In [100]:
 ### MISSING DATA ##
A={
    'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]
}
df=pd.DataFrame(A)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [101]:
df.isnull()  ## shows null values

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [102]:
df.dropna() ##helps to remove the rows of null values default axis = 0 perform on rows

A    B  C
0  1.0  5.0  1

In [103]:
df.dropna(axis=1) ## helps to perform on columns

C
0  1
1  2
2  3

In [104]:
df.dropna(axis = 1, thresh = 0)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [105]:
df.fillna(value=1,axis=0, limit=1)

A    B  C
0  1.0  5.0  1
1  2.0  1.0  2
2  1.0  NaN  3

In [106]:
## assigning missing values by mean of a column 
df[['A','B']].fillna(value=df[['A','B']].mean())

A    B
0  1.0  5.0
1  2.0  5.0
2  1.5  5.0

In [107]:
##GROUPBY###

In [ ]:
df.groupby('Groups').describe()

In [ ]:
df.groupby('Groups').describe().transpose()

In [ ]:
df.std().max()
df.min()

In [ ]:
df.groupby('Groups').count()

In [ ]:
###joins##

In [109]:
df1=pd.DataFrame({
    'A':['A0','A1','A3'],
    'B':['B0','B1','B2'],
    'k1':[1,2,3]},
                index= ['k0', 'k1','k2'])
df2=pd.DataFrame({
    'C':['C0','C1','C2'],
    'D':['D0','D1','D2'],
    'k2':[0,2,1]}, 
                 index= ['k0', 'k1','k2'])
     
df1.join(df2) ## default perform inner join

A   B  k1   C   D  k2
k0  A0  B0   1  C0  D0   0
k1  A1  B1   2  C1  D1   2
k2  A3  B2   3  C2  D2   1

In [ ]:
#df1.join(df2, on = ['k1'], how='left')
df1.join(df2, how='left')

In [ ]:
###### operations -- DataFrame ###########

In [112]:
df1.columns ## shows the column name

Index(['A', 'B', 'k1'], dtype='object')

In [ ]:
df2.index  ## method for showcase index 

In [113]:
df1['A'].apply(len)

k0    2
k1    2
k2    2
Name: A, dtype: int64

In [114]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [115]:
df['A'].apply(lambda x:x*2)

0    2.0
1    4.0
2    NaN
Name: A, dtype: float64

In [117]:
df2.sort_values('k2')  ## sorting operation

C   D  k2
k0  C0  D0   0
k2  C2  D2   1
k1  C1  D1   2

In [116]:
df.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
### DATA INPUT AND OUTPUT ###

pip install sqlalchemy
pip install lxml
pip install html5lib
pip install BeautifulSoup4

In [ ]:
pip install xlrd